(cl:defpackage beginner_tutorials-msg
  (:use )
  (:export
   "<AREA>"
   "AREA"
   "<FIBONACCIACTION>"
   "FIBONACCIACTION"
   "<FIBONACCIACTIONFEEDBACK>"
   "FIBONACCIACTIONFEEDBACK"
   "<FIBONACCIACTIONGOAL>"
   "FIBONACCIACTIONGOAL"
   "<FIBONACCIACTIONRESULT>"
   "FIBONACCIACTIONRESULT"
   "<FIBONACCIFEEDBACK>"
   "FIBONACCIFEEDBACK"
   "<FIBONACCIGOAL>"
   "FIBONACCIGOAL"
   "<FIBONACCIRESULT>"
   "FIBONACCIRESULT"
   "<NUM>"
   "NUM"
  ))

