// Generated by gencpp from file new_msgs/student.msg
// DO NOT EDIT!


#ifndef NEW_MSGS_MESSAGE_STUDENT_H
#define NEW_MSGS_MESSAGE_STUDENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace new_msgs
{
template <class ContainerAllocator>
struct student_
{
  typedef student_<ContainerAllocator> Type;

  student_()
    : name()
    , age(0)  {
    }
  student_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , age(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef int64_t _age_type;
  _age_type age;





  typedef boost::shared_ptr< ::new_msgs::student_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::new_msgs::student_<ContainerAllocator> const> ConstPtr;

}; // struct student_

typedef ::new_msgs::student_<std::allocator<void> > student;

typedef boost::shared_ptr< ::new_msgs::student > studentPtr;
typedef boost::shared_ptr< ::new_msgs::student const> studentConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::new_msgs::student_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::new_msgs::student_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::new_msgs::student_<ContainerAllocator1> & lhs, const ::new_msgs::student_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.age == rhs.age;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::new_msgs::student_<ContainerAllocator1> & lhs, const ::new_msgs::student_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace new_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::new_msgs::student_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::new_msgs::student_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::new_msgs::student_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::new_msgs::student_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::new_msgs::student_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::new_msgs::student_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::new_msgs::student_<ContainerAllocator> >
{
  static const char* value()
  {
    return "777a0ba04feb2b848668b8ed180bf7eb";
  }

  static const char* value(const ::new_msgs::student_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x777a0ba04feb2b84ULL;
  static const uint64_t static_value2 = 0x8668b8ed180bf7ebULL;
};

template<class ContainerAllocator>
struct DataType< ::new_msgs::student_<ContainerAllocator> >
{
  static const char* value()
  {
    return "new_msgs/student";
  }

  static const char* value(const ::new_msgs::student_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::new_msgs::student_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"int64 age\n"
;
  }

  static const char* value(const ::new_msgs::student_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::new_msgs::student_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.age);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct student_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::new_msgs::student_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::new_msgs::student_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "age: ";
    Printer<int64_t>::stream(s, indent + "  ", v.age);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEW_MSGS_MESSAGE_STUDENT_H
